In [ ]:
#Importing pandas for data manipulation and numpy for vector operations
#Importing Standard Scalar for normalisation 
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [79]:
#Importing uncleaned laptop Price dataset: https://www.kaggle.com/datasets/ehtishamsadiq/uncleaned-laptop-price-dataset

df = pd.read_csv("laptopData.csv")

In [80]:
#Dispalying the first 5 records of the dataframe
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [81]:
#Displaying the infomation of the dataframe: includes number of entries, number of columns 
#as well as datatypes and other properties of attributes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1273 non-null   float64
 1   Company           1273 non-null   object
 2   TypeName          1273 non-null   object
 3   Inches            1273 non-null   object
 4   ScreenResolution  1273 non-null   object
 5   Cpu               1273 non-null   object
 6   Ram               1273 non-null   object
 7   Memory            1273 non-null   object
 8   Gpu               1273 non-null   object
 9   OpSys             1273 non-null   object
 10  Weight            1273 non-null   object
 11  Price             1273 non-null   float64
dtypes: float64(2), object(10)
memory usage: 122.3+ KB

In [82]:
#The dataframe consists of numeric as well as categorical data, describing all the data
df.describe(include='all')

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
count,1273.000000,1273,1273,1273,1273,1273,1273,1273,1273,1273,1273,1273.000000
unique,NaN,19,6,25,40,118,10,40,110,9,189,NaN
top,NaN,Lenovo,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,2.2kg,NaN
freq,NaN,290,710,640,495,183,601,401,271,1047,111,NaN
mean,652.674784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59955.814073
std,376.493027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37332.251005
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9270.720000
25%,327.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31914.720000
50%,652.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52161.120000
75%,980.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79333.387200
max,1302.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,324954.720000

In [83]:
#Displaying the number of null values in each attribute to pre-process data
df.isnull().sum()

Unnamed: 0          30
Company             30
TypeName            30
Inches              30
ScreenResolution    30
Cpu                 30
Ram                 30
Memory              30
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

In [84]:
#Data Cleaning: Dropping the unnamed column from the dataframe
df = df.drop(columns=['Unnamed: 0'])

In [85]:
#The Inches attribute is an object type hence converting it to numeric using pd.to_numeric
#Inches column has '?' values so replacing those with NaN
#Replacing all NaN values in Inches column with the mean of the column using fillna
df['Inches'] = df['Inches'].replace('?', np.nan)
df['Inches'] = pd.to_numeric(df['Inches'], errors='coerce')
df['Inches'] = df['Inches'].fillna(df['Inches'].mean())

#The Weight column is of object datatype in the form "25 kg"
#Hence we replace the kg with empty string '' using str.replace
#We remove '?' values with NaN using replace
#Replace all NaN values with mean of the Weight column
df['Weight'] = df['Weight'].replace('?', np.nan)
df['Weight'] = df['Weight'].str.replace('kg', '', regex=False)
df['Weight'] = pd.to_numeric(df['Weight'], errors='coerce')
df['Weight'] = df['Weight'].fillna(df['Weight'].mean())

#Replacing all NaN values in Price column with its mean
df['Price'] = df['Price'].fillna(df['Price'].mean())

In [16]:
#num_cols = ['Unnamed: 0', 'Price', 'Inches', 'Weight']
#for col in num_cols:
 #   df[col] = df[col].fillna(df[col].mean())

In [86]:
#There esists categorical data in the dataset
#Replacing the NaN mode (highest frequency values of that columns hence mode()[0] since we replace with single value not Series)
cat_cols = ['Company', 'TypeName', 'ScreenResolution', 'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys']
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [87]:
#Chceking if the data cleaning removed NaN values in all attributes
df.isna().sum()

Company             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price               0
dtype: int64

In [88]:
#Performing Aggregation on the numeric columns to find mean, median, minimum, maximum and standard deviation
df[['Price', 'Inches', 'Weight']].agg(['mean', 'median', 'min', 'max', 'std'])

                Price     Inches     Weight
mean     59955.814073  15.130818   2.077618
median   52747.200000  15.600000   2.060000
min       9270.720000  10.100000   0.000200
max     324954.720000  35.600000  11.100000
std      36899.649480   1.931029   0.798133

In [89]:
#Finding the mean price of laptops of each company using groupby
df.groupby('Company')['Price'].mean()

Company
Acer          33394.615969
Apple         83340.499886
Asus          58972.373723
Chuwi         16745.726400
Dell          63237.061079
Fujitsu       38574.720000
Google        89386.080000
HP            57214.371465
Huawei        75870.720000
LG           111834.720000
Lenovo        58249.040039
MSI           91814.548891
Mediacom      15717.600000
Microsoft     85903.788000
Razer        178282.491429
Samsung       75308.320000
Toshiba       66747.370213
Vero          11584.404000
Xiaomi        60390.882000
Name: Price, dtype: float64

In [ ]:
#Filtering out which Dell laptops are less than 20,000
df[(df['Company'] == 'Dell') & (df['Price'] < 20000)]

,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
340,Dell,Notebook,15.6,1366x768,Intel Celeron Dual Core N3060 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Linux,2.20,14646.672
377,Dell,Notebook,15.6,1366x768,Intel Celeron Dual Core N3060 1.60GHz,4GB,500GB HDD,Intel HD Graphics 400,Windows 10,1.80,16463.520
584,Dell,Netbook,11.6,1366x768,Intel Celeron Dual Core N3060 1.6GHz,4GB,16GB Flash Storage,Intel HD Graphics 400,Chrome OS,1.26,15717.600
613,Dell,Notebook,15.6,1366x768,Intel Core i3 6006U 2.0GHz,4GB,1TB HDD,Intel HD Graphics 520,Linux,2.25,19127.520
884,Dell,Notebook,15.6,1366x768,Intel Pentium Quad Core N3710 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.20,19660.320
1250,Dell,Notebook,15.6,1366x768,Intel Pentium Quad Core N3710 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Linux,2.20,17262.720

In [91]:
#Normalising Weight attribute using standard Scalar
scaler = StandardScaler()
df['Weight_std'] = scaler.fit_transform(df[['Weight']])

In [92]:
#Values less than mean of Weight are negative
#values equal to mean are 0
#Values greater than mean values are positive
df['Weight_std']

0      -0.886932
1      -0.924534
2      -0.272764
3      -0.310366
4      -0.886932
          ...
1298   -0.347968
1299   -0.974670
1300   -0.723989
1301    0.140860
1302    0.153394
Name: Weight_std, Length: 1303, dtype: float64

In [64]:
#Finding the weight of least weight laptops of all companies
df.groupby('Company')['Weight_std'].min()

Company
Acer        -1.200283
Apple       -1.450964
Asus        -1.463498
Chuwi       -0.849330
Dell        -2.603846
Fujitsu      0.153394
Google      -1.225351
HP          -1.388294
Huawei      -1.288021
LG          -1.375760
Lenovo      -1.739247
MSI         -0.598649
Mediacom    -1.150147
Microsoft   -1.037340
Razer       -1.037340
Samsung     -1.588838
Toshiba     -1.288021
Vero        -1.074943
Xiaomi      -0.999738
Name: Weight_std, dtype: float64

In [93]:
#Finding the light weight lqaptops count of each company
df[df['Weight_std'] < 0].groupby('Company').size()

Company
Acer          27
Apple         21
Asus          71
Chuwi          3
Dell         123
Google         3
HP           185
Huawei         2
LG             3
Lenovo       173
MSI            7
Mediacom       7
Microsoft      6
Razer          5
Samsung        8
Toshiba       36
Vero           4
Xiaomi         4
dtype: int64

In [71]:
#Finding the heavy weight lqaptops count of each company
df[df['Weight_std'] > 0].groupby('Company').size()

Company
Acer        76
Asus        85
Dell       164
Fujitsu      2
HP          81
Lenovo     147
MSI         46
Razer        2
Samsung      1
Toshiba     11
dtype: int64